import First from '@/components/first'
import Fourth from '@/components/fourth'
import Second from '@/components/second'
import Third from '@/components/third'
import Head from 'next/head'
import Space from './space'


export default function Home() {
  return (
    <>
      <Head>
        <title>Space-X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <First />
        <Second />
        <Third />
        <Fourth />
      </main>
    </>
  )
}
